alias bc='bc -lq ~/*.bc'
alias bvets='cocot /cygdrive/c/Users/hakehash/Documents/BveTs/BveTs.exe'
alias display='~/iview441_x64/i_view64.exe'
alias eliza='clisp ~/elizagen/coselleliza1969and1972.lisp'
alias gnuplot='console gnuplot'
alias gs='/cygdrive/c/Program\ Files/gs/gs9.16/bin/gswin64c.exe'
alias gsv='/cygdrive/c/Program\ Files/Ghostgum/gsview/gsview64.exe'
alias jnethack='console ~/jnethack-3.6.0-0.4-win/JNetHack.exe'
alias ls='ls -h --color=tty'
alias opera='/cygdrive/c/Program\ Files/Opera\ x64/opera.exe &amp;'
alias usleep='busybox usleep'
#alias vi='xvi'
alias vivaldi='/cygdrive/c/Program\ Files/Vivaldi/Application/vivaldi.exe'
alias wput='wput -u -N'
export PS1='\[\e]0;\w\a\]\[\e[32m\]\t \[\e[33m\]\w\[\e[0m\] \$ '
umask 002
